// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/list/list.proto

package list

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Performs n >= 1 actions on lists by ID
type MultiListRequest struct {
	ListIds              []int64  `protobuf:"varint,1,rep,packed,name=ListIds,proto3" json:"ListIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MultiListRequest) Reset()         { *m = MultiListRequest{} }
func (m *MultiListRequest) String() string { return proto.CompactTextString(m) }
func (*MultiListRequest) ProtoMessage()    {}
func (*MultiListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00b033104bd41f5a, []int{0}
}

func (m *MultiListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiListRequest.Unmarshal(m, b)
}
func (m *MultiListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiListRequest.Marshal(b, m, deterministic)
}
func (m *MultiListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiListRequest.Merge(m, src)
}
func (m *MultiListRequest) XXX_Size() int {
	return xxx_messageInfo_MultiListRequest.Size(m)
}
func (m *MultiListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MultiListRequest proto.InternalMessageInfo

func (m *MultiListRequest) GetListIds() []int64 {
	if m != nil {
		return m.ListIds
	}
	return nil
}

// A list of lists
type MultiList struct {
	Lists                []*List  `protobuf:"bytes,1,rep,name=Lists,proto3" json:"Lists,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MultiList) Reset()         { *m = MultiList{} }
func (m *MultiList) String() string { return proto.CompactTextString(m) }
func (*MultiList) ProtoMessage()    {}
func (*MultiList) Descriptor() ([]byte, []int) {
	return fileDescriptor_00b033104bd41f5a, []int{1}
}

func (m *MultiList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiList.Unmarshal(m, b)
}
func (m *MultiList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiList.Marshal(b, m, deterministic)
}
func (m *MultiList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiList.Merge(m, src)
}
func (m *MultiList) XXX_Size() int {
	return xxx_messageInfo_MultiList.Size(m)
}
func (m *MultiList) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiList.DiscardUnknown(m)
}

var xxx_messageInfo_MultiList proto.InternalMessageInfo

func (m *MultiList) GetLists() []*List {
	if m != nil {
		return m.Lists
	}
	return nil
}

type List struct {
	ListName             string               `protobuf:"bytes,1,opt,name=ListName,proto3" json:"ListName,omitempty"`
	ListId               int64                `protobuf:"varint,2,opt,name=ListId,proto3" json:"ListId,omitempty"`
	ListUser             string               `protobuf:"bytes,3,opt,name=ListUser,proto3" json:"ListUser,omitempty"`
	ListTasks            []*Task              `protobuf:"bytes,4,rep,name=ListTasks,proto3" json:"ListTasks,omitempty"`
	ListCreated          *timestamp.Timestamp `protobuf:"bytes,5,opt,name=ListCreated,proto3" json:"ListCreated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *List) Reset()         { *m = List{} }
func (m *List) String() string { return proto.CompactTextString(m) }
func (*List) ProtoMessage()    {}
func (*List) Descriptor() ([]byte, []int) {
	return fileDescriptor_00b033104bd41f5a, []int{2}
}

func (m *List) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_List.Unmarshal(m, b)
}
func (m *List) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_List.Marshal(b, m, deterministic)
}
func (m *List) XXX_Merge(src proto.Message) {
	xxx_messageInfo_List.Merge(m, src)
}
func (m *List) XXX_Size() int {
	return xxx_messageInfo_List.Size(m)
}
func (m *List) XXX_DiscardUnknown() {
	xxx_messageInfo_List.DiscardUnknown(m)
}

var xxx_messageInfo_List proto.InternalMessageInfo

func (m *List) GetListName() string {
	if m != nil {
		return m.ListName
	}
	return ""
}

func (m *List) GetListId() int64 {
	if m != nil {
		return m.ListId
	}
	return 0
}

func (m *List) GetListUser() string {
	if m != nil {
		return m.ListUser
	}
	return ""
}

func (m *List) GetListTasks() []*Task {
	if m != nil {
		return m.ListTasks
	}
	return nil
}

func (m *List) GetListCreated() *timestamp.Timestamp {
	if m != nil {
		return m.ListCreated
	}
	return nil
}

// ListTasks to complete
type Task struct {
	TaskId               int64                `protobuf:"varint,1,opt,name=TaskId,proto3" json:"TaskId,omitempty"`
	TaskDescription      string               `protobuf:"bytes,2,opt,name=TaskDescription,proto3" json:"TaskDescription,omitempty"`
	TaskComplete         bool                 `protobuf:"varint,3,opt,name=TaskComplete,proto3" json:"TaskComplete,omitempty"`
	TaskCreated          *timestamp.Timestamp `protobuf:"bytes,4,opt,name=TaskCreated,proto3" json:"TaskCreated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Task) Reset()         { *m = Task{} }
func (m *Task) String() string { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()    {}
func (*Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_00b033104bd41f5a, []int{3}
}

func (m *Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Task.Unmarshal(m, b)
}
func (m *Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Task.Marshal(b, m, deterministic)
}
func (m *Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Task.Merge(m, src)
}
func (m *Task) XXX_Size() int {
	return xxx_messageInfo_Task.Size(m)
}
func (m *Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Task proto.InternalMessageInfo

func (m *Task) GetTaskId() int64 {
	if m != nil {
		return m.TaskId
	}
	return 0
}

func (m *Task) GetTaskDescription() string {
	if m != nil {
		return m.TaskDescription
	}
	return ""
}

func (m *Task) GetTaskComplete() bool {
	if m != nil {
		return m.TaskComplete
	}
	return false
}

func (m *Task) GetTaskCreated() *timestamp.Timestamp {
	if m != nil {
		return m.TaskCreated
	}
	return nil
}

// Takes in a creator name (extension to a users service would be a logical next step)
type CreateListsRequest struct {
	ListName             string   `protobuf:"bytes,1,opt,name=ListName,proto3" json:"ListName,omitempty"`
	ListUser             string   `protobuf:"bytes,2,opt,name=ListUser,proto3" json:"ListUser,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateListsRequest) Reset()         { *m = CreateListsRequest{} }
func (m *CreateListsRequest) String() string { return proto.CompactTextString(m) }
func (*CreateListsRequest) ProtoMessage()    {}
func (*CreateListsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00b033104bd41f5a, []int{4}
}

func (m *CreateListsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateListsRequest.Unmarshal(m, b)
}
func (m *CreateListsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateListsRequest.Marshal(b, m, deterministic)
}
func (m *CreateListsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateListsRequest.Merge(m, src)
}
func (m *CreateListsRequest) XXX_Size() int {
	return xxx_messageInfo_CreateListsRequest.Size(m)
}
func (m *CreateListsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateListsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateListsRequest proto.InternalMessageInfo

func (m *CreateListsRequest) GetListName() string {
	if m != nil {
		return m.ListName
	}
	return ""
}

func (m *CreateListsRequest) GetListUser() string {
	if m != nil {
		return m.ListUser
	}
	return ""
}

// Returns ID of newly created list
type CreateListResponse struct {
	ListId               int64         `protobuf:"varint,1,opt,name=ListId,proto3" json:"ListId,omitempty"`
	Response             *BaseResponse `protobuf:"bytes,2,opt,name=Response,proto3" json:"Response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CreateListResponse) Reset()         { *m = CreateListResponse{} }
func (m *CreateListResponse) String() string { return proto.CompactTextString(m) }
func (*CreateListResponse) ProtoMessage()    {}
func (*CreateListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00b033104bd41f5a, []int{5}
}

func (m *CreateListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateListResponse.Unmarshal(m, b)
}
func (m *CreateListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateListResponse.Marshal(b, m, deterministic)
}
func (m *CreateListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateListResponse.Merge(m, src)
}
func (m *CreateListResponse) XXX_Size() int {
	return xxx_messageInfo_CreateListResponse.Size(m)
}
func (m *CreateListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateListResponse proto.InternalMessageInfo

func (m *CreateListResponse) GetListId() int64 {
	if m != nil {
		return m.ListId
	}
	return 0
}

func (m *CreateListResponse) GetResponse() *BaseResponse {
	if m != nil {
		return m.Response
	}
	return nil
}

// Contains a List ID and the tasks to be associated with it. All tasks are assumed to be incomplete upon creation
type AddTasksToListRequest struct {
	ListId               int64    `protobuf:"varint,1,opt,name=ListId,proto3" json:"ListId,omitempty"`
	TaskDescriptions     []string `protobuf:"bytes,2,rep,name=TaskDescriptions,proto3" json:"TaskDescriptions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddTasksToListRequest) Reset()         { *m = AddTasksToListRequest{} }
func (m *AddTasksToListRequest) String() string { return proto.CompactTextString(m) }
func (*AddTasksToListRequest) ProtoMessage()    {}
func (*AddTasksToListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00b033104bd41f5a, []int{6}
}

func (m *AddTasksToListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddTasksToListRequest.Unmarshal(m, b)
}
func (m *AddTasksToListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddTasksToListRequest.Marshal(b, m, deterministic)
}
func (m *AddTasksToListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddTasksToListRequest.Merge(m, src)
}
func (m *AddTasksToListRequest) XXX_Size() int {
	return xxx_messageInfo_AddTasksToListRequest.Size(m)
}
func (m *AddTasksToListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddTasksToListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddTasksToListRequest proto.InternalMessageInfo

func (m *AddTasksToListRequest) GetListId() int64 {
	if m != nil {
		return m.ListId
	}
	return 0
}

func (m *AddTasksToListRequest) GetTaskDescriptions() []string {
	if m != nil {
		return m.TaskDescriptions
	}
	return nil
}

// Returns the IDs of newly created lists
type AddTasksToListResponse struct {
	TaskIds              []int64       `protobuf:"varint,1,rep,packed,name=TaskIds,proto3" json:"TaskIds,omitempty"`
	Response             *BaseResponse `protobuf:"bytes,2,opt,name=Response,proto3" json:"Response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *AddTasksToListResponse) Reset()         { *m = AddTasksToListResponse{} }
func (m *AddTasksToListResponse) String() string { return proto.CompactTextString(m) }
func (*AddTasksToListResponse) ProtoMessage()    {}
func (*AddTasksToListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00b033104bd41f5a, []int{7}
}

func (m *AddTasksToListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddTasksToListResponse.Unmarshal(m, b)
}
func (m *AddTasksToListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddTasksToListResponse.Marshal(b, m, deterministic)
}
func (m *AddTasksToListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddTasksToListResponse.Merge(m, src)
}
func (m *AddTasksToListResponse) XXX_Size() int {
	return xxx_messageInfo_AddTasksToListResponse.Size(m)
}
func (m *AddTasksToListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddTasksToListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddTasksToListResponse proto.InternalMessageInfo

func (m *AddTasksToListResponse) GetTaskIds() []int64 {
	if m != nil {
		return m.TaskIds
	}
	return nil
}

func (m *AddTasksToListResponse) GetResponse() *BaseResponse {
	if m != nil {
		return m.Response
	}
	return nil
}

// Takes in a series of Task IDs and flips their completed status
type ToggleTaskRequest struct {
	TaskIds              []int64  `protobuf:"varint,1,rep,packed,name=TaskIds,proto3" json:"TaskIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ToggleTaskRequest) Reset()         { *m = ToggleTaskRequest{} }
func (m *ToggleTaskRequest) String() string { return proto.CompactTextString(m) }
func (*ToggleTaskRequest) ProtoMessage()    {}
func (*ToggleTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00b033104bd41f5a, []int{8}
}

func (m *ToggleTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ToggleTaskRequest.Unmarshal(m, b)
}
func (m *ToggleTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ToggleTaskRequest.Marshal(b, m, deterministic)
}
func (m *ToggleTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ToggleTaskRequest.Merge(m, src)
}
func (m *ToggleTaskRequest) XXX_Size() int {
	return xxx_messageInfo_ToggleTaskRequest.Size(m)
}
func (m *ToggleTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ToggleTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ToggleTaskRequest proto.InternalMessageInfo

func (m *ToggleTaskRequest) GetTaskIds() []int64 {
	if m != nil {
		return m.TaskIds
	}
	return nil
}

// Returns the updated task statuses
type ToggleTaskResponse struct {
	ListTasks            []*Task       `protobuf:"bytes,1,rep,name=ListTasks,proto3" json:"ListTasks,omitempty"`
	Response             *BaseResponse `protobuf:"bytes,2,opt,name=Response,proto3" json:"Response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ToggleTaskResponse) Reset()         { *m = ToggleTaskResponse{} }
func (m *ToggleTaskResponse) String() string { return proto.CompactTextString(m) }
func (*ToggleTaskResponse) ProtoMessage()    {}
func (*ToggleTaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00b033104bd41f5a, []int{9}
}

func (m *ToggleTaskResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ToggleTaskResponse.Unmarshal(m, b)
}
func (m *ToggleTaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ToggleTaskResponse.Marshal(b, m, deterministic)
}
func (m *ToggleTaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ToggleTaskResponse.Merge(m, src)
}
func (m *ToggleTaskResponse) XXX_Size() int {
	return xxx_messageInfo_ToggleTaskResponse.Size(m)
}
func (m *ToggleTaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ToggleTaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ToggleTaskResponse proto.InternalMessageInfo

func (m *ToggleTaskResponse) GetListTasks() []*Task {
	if m != nil {
		return m.ListTasks
	}
	return nil
}

func (m *ToggleTaskResponse) GetResponse() *BaseResponse {
	if m != nil {
		return m.Response
	}
	return nil
}

// Common fields used by many endpoint responses
type BaseResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	Error                bool     `protobuf:"varint,2,opt,name=Error,proto3" json:"Error,omitempty"`
	ErrorMessage         string   `protobuf:"bytes,3,opt,name=ErrorMessage,proto3" json:"ErrorMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseResponse) Reset()         { *m = BaseResponse{} }
func (m *BaseResponse) String() string { return proto.CompactTextString(m) }
func (*BaseResponse) ProtoMessage()    {}
func (*BaseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00b033104bd41f5a, []int{10}
}

func (m *BaseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseResponse.Unmarshal(m, b)
}
func (m *BaseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseResponse.Marshal(b, m, deterministic)
}
func (m *BaseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseResponse.Merge(m, src)
}
func (m *BaseResponse) XXX_Size() int {
	return xxx_messageInfo_BaseResponse.Size(m)
}
func (m *BaseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BaseResponse proto.InternalMessageInfo

func (m *BaseResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *BaseResponse) GetError() bool {
	if m != nil {
		return m.Error
	}
	return false
}

func (m *BaseResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func init() {
	proto.RegisterType((*MultiListRequest)(nil), "list.MultiListRequest")
	proto.RegisterType((*MultiList)(nil), "list.MultiList")
	proto.RegisterType((*List)(nil), "list.List")
	proto.RegisterType((*Task)(nil), "list.Task")
	proto.RegisterType((*CreateListsRequest)(nil), "list.CreateListsRequest")
	proto.RegisterType((*CreateListResponse)(nil), "list.CreateListResponse")
	proto.RegisterType((*AddTasksToListRequest)(nil), "list.AddTasksToListRequest")
	proto.RegisterType((*AddTasksToListResponse)(nil), "list.AddTasksToListResponse")
	proto.RegisterType((*ToggleTaskRequest)(nil), "list.ToggleTaskRequest")
	proto.RegisterType((*ToggleTaskResponse)(nil), "list.ToggleTaskResponse")
	proto.RegisterType((*BaseResponse)(nil), "list.BaseResponse")
}

func init() { proto.RegisterFile("proto/list/list.proto", fileDescriptor_00b033104bd41f5a) }

var fileDescriptor_00b033104bd41f5a = []byte{
	// 552 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xcd, 0x8e, 0xd3, 0x3c,
	0x14, 0x6d, 0x9a, 0x76, 0xa6, 0xbd, 0x19, 0x7d, 0x33, 0x9f, 0xc5, 0x14, 0x2b, 0x20, 0x11, 0x79,
	0x15, 0x21, 0x26, 0x95, 0x8a, 0xd8, 0xb1, 0xa1, 0x03, 0x42, 0x23, 0x4d, 0x59, 0x98, 0xb2, 0x82,
	0x4d, 0x3a, 0x31, 0x51, 0x44, 0x5a, 0x87, 0xd8, 0xe5, 0x65, 0x78, 0x03, 0x1e, 0x82, 0x67, 0x43,
	0xb6, 0xe3, 0xfc, 0xb5, 0x0c, 0x9a, 0x4d, 0xe3, 0x73, 0xef, 0xf5, 0xf5, 0xf1, 0x3d, 0xc7, 0x85,
	0xcb, 0xa2, 0xe4, 0x92, 0xcf, 0xf3, 0x4c, 0x48, 0xfd, 0x13, 0x69, 0x8c, 0x46, 0x6a, 0xed, 0x3f,
	0x4b, 0x39, 0x4f, 0x73, 0x36, 0xd7, 0xb1, 0xcd, 0xfe, 0xeb, 0x5c, 0x66, 0x5b, 0x26, 0x64, 0xbc,
	0x2d, 0x4c, 0x19, 0x79, 0x01, 0x17, 0xab, 0x7d, 0x2e, 0xb3, 0xdb, 0x4c, 0x48, 0xca, 0xbe, 0xef,
	0x99, 0x90, 0x08, 0xc3, 0xa9, 0x82, 0x37, 0x89, 0xc0, 0x4e, 0xe0, 0x86, 0x2e, 0xb5, 0x90, 0x5c,
	0xc1, 0xb4, 0xae, 0x46, 0x01, 0x8c, 0xd5, 0xd7, 0x14, 0x79, 0x0b, 0x88, 0xf4, 0xe9, 0xba, 0x91,
	0x49, 0x90, 0xdf, 0x0e, 0x8c, 0x74, 0xa9, 0x0f, 0x13, 0xf5, 0xfd, 0x10, 0x6f, 0x19, 0x76, 0x02,
	0x27, 0x9c, 0xd2, 0x1a, 0xa3, 0x19, 0x9c, 0x98, 0xf6, 0x78, 0x18, 0x38, 0xa1, 0x4b, 0x2b, 0x64,
	0xf7, 0x7c, 0x12, 0xac, 0xc4, 0x6e, 0xb3, 0x47, 0x61, 0x14, 0xc2, 0x54, 0xad, 0xd7, 0xb1, 0xf8,
	0x26, 0xf0, 0xa8, 0x7d, 0xbc, 0x0a, 0xd1, 0x26, 0x89, 0x5e, 0x83, 0xa7, 0xc0, 0x75, 0xc9, 0x62,
	0xc9, 0x12, 0x3c, 0x0e, 0x9c, 0xd0, 0x5b, 0xf8, 0x91, 0x19, 0x4b, 0x64, 0xc7, 0x12, 0xad, 0xed,
	0x58, 0x68, 0xbb, 0x9c, 0xfc, 0x72, 0x60, 0xa4, 0xfa, 0x28, 0x92, 0xea, 0x7b, 0x93, 0x68, 0xfa,
	0x2e, 0xad, 0x10, 0x0a, 0xe1, 0x5c, 0xad, 0xde, 0x32, 0x71, 0x57, 0x66, 0x85, 0xcc, 0xf8, 0x4e,
	0xdf, 0x62, 0x4a, 0xfb, 0x61, 0x44, 0xe0, 0x4c, 0x85, 0xae, 0xf9, 0xb6, 0xc8, 0x99, 0x64, 0xfa,
	0x4a, 0x13, 0xda, 0x89, 0x29, 0xb2, 0x1a, 0x57, 0x64, 0x47, 0xff, 0x26, 0xdb, 0x2a, 0x27, 0xb7,
	0x80, 0xcc, 0x52, 0x0f, 0xdf, 0x8a, 0x79, 0xdf, 0xe8, 0xdb, 0x23, 0x1e, 0x76, 0x47, 0x4c, 0xbe,
	0xb4, 0xbb, 0x51, 0x26, 0x0a, 0xbe, 0x13, 0x6d, 0xb1, 0x9c, 0x8e, 0x58, 0x11, 0x4c, 0x6c, 0x8d,
	0xee, 0xe4, 0x2d, 0x90, 0xd1, 0x63, 0x19, 0x0b, 0x66, 0x33, 0xb4, 0xae, 0x21, 0x9f, 0xe1, 0xf2,
	0x4d, 0x92, 0x68, 0x89, 0xd6, 0xbc, 0xed, 0xbd, 0xbf, 0x1d, 0xf0, 0x1c, 0x2e, 0x7a, 0x13, 0x15,
	0x78, 0x18, 0xb8, 0xe1, 0x94, 0x1e, 0xc4, 0xc9, 0x06, 0x66, 0xfd, 0xe6, 0x15, 0x7d, 0x0c, 0xa7,
	0x46, 0xb8, 0xda, 0xd9, 0x15, 0x7c, 0xf0, 0x05, 0xae, 0xe0, 0xff, 0x35, 0x4f, 0xd3, 0x9c, 0x69,
	0xc3, 0x35, 0x0f, 0xe7, 0x78, 0x7b, 0xb2, 0x03, 0xd4, 0x2e, 0xaf, 0xe8, 0x74, 0x6c, 0xec, 0xdc,
	0x67, 0xe3, 0x87, 0xd2, 0xdb, 0xc0, 0x59, 0x3b, 0xa3, 0x98, 0xad, 0x98, 0x10, 0x71, 0x6a, 0x4d,
	0x60, 0x21, 0x7a, 0x04, 0xe3, 0x77, 0x65, 0xc9, 0x8d, 0x01, 0x26, 0xd4, 0x00, 0xe5, 0x56, 0xbd,
	0xb0, 0x9b, 0xcc, 0x03, 0xec, 0xc4, 0x16, 0x3f, 0x87, 0xe6, 0x6d, 0x7d, 0x64, 0xe5, 0x8f, 0xec,
	0x8e, 0xa1, 0x25, 0x40, 0xe3, 0x18, 0x84, 0x0d, 0xbf, 0x43, 0x47, 0xfa, 0x07, 0x99, 0x9a, 0xf5,
	0x00, 0xad, 0xe0, 0xbf, 0xae, 0x74, 0xe8, 0x89, 0xa9, 0x3e, 0xea, 0x16, 0xff, 0xe9, 0xf1, 0x64,
	0xdd, 0xee, 0x15, 0x4c, 0xde, 0x33, 0xa9, 0x4f, 0x47, 0x33, 0x53, 0xdb, 0xff, 0xb7, 0xf3, 0xcf,
	0x7b, 0x71, 0x32, 0x40, 0x4b, 0xf0, 0x1a, 0xb5, 0x04, 0x7a, 0x5c, 0x69, 0xd2, 0xd7, 0xdb, 0xde,
	0xe4, 0x50, 0x59, 0x32, 0xd8, 0x9c, 0xe8, 0xe7, 0xfa, 0xf2, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x0c, 0x07, 0x01, 0xa6, 0x9f, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ListServiceClient is the client API for ListService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ListServiceClient interface {
	// Saves a single list for a given user
	CreateList(ctx context.Context, in *CreateListsRequest, opts ...grpc.CallOption) (*CreateListResponse, error)
	// Saves n >= 1 task descriptions to an extant List
	AddTasksToList(ctx context.Context, in *AddTasksToListRequest, opts ...grpc.CallOption) (*AddTasksToListResponse, error)
	// Gets information about n >= 1 lists by ID lookup
	GetLists(ctx context.Context, in *MultiListRequest, opts ...grpc.CallOption) (*MultiList, error)
	// Flips the completion status of n >= 1 task
	ToggleTasks(ctx context.Context, in *ToggleTaskRequest, opts ...grpc.CallOption) (*ToggleTaskResponse, error)
}

type listServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewListServiceClient(cc grpc.ClientConnInterface) ListServiceClient {
	return &listServiceClient{cc}
}

func (c *listServiceClient) CreateList(ctx context.Context, in *CreateListsRequest, opts ...grpc.CallOption) (*CreateListResponse, error) {
	out := new(CreateListResponse)
	err := c.cc.Invoke(ctx, "/list.ListService/CreateList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *listServiceClient) AddTasksToList(ctx context.Context, in *AddTasksToListRequest, opts ...grpc.CallOption) (*AddTasksToListResponse, error) {
	out := new(AddTasksToListResponse)
	err := c.cc.Invoke(ctx, "/list.ListService/AddTasksToList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *listServiceClient) GetLists(ctx context.Context, in *MultiListRequest, opts ...grpc.CallOption) (*MultiList, error) {
	out := new(MultiList)
	err := c.cc.Invoke(ctx, "/list.ListService/GetLists", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *listServiceClient) ToggleTasks(ctx context.Context, in *ToggleTaskRequest, opts ...grpc.CallOption) (*ToggleTaskResponse, error) {
	out := new(ToggleTaskResponse)
	err := c.cc.Invoke(ctx, "/list.ListService/ToggleTasks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ListServiceServer is the server API for ListService service.
type ListServiceServer interface {
	// Saves a single list for a given user
	CreateList(context.Context, *CreateListsRequest) (*CreateListResponse, error)
	// Saves n >= 1 task descriptions to an extant List
	AddTasksToList(context.Context, *AddTasksToListRequest) (*AddTasksToListResponse, error)
	// Gets information about n >= 1 lists by ID lookup
	GetLists(context.Context, *MultiListRequest) (*MultiList, error)
	// Flips the completion status of n >= 1 task
	ToggleTasks(context.Context, *ToggleTaskRequest) (*ToggleTaskResponse, error)
}

// UnimplementedListServiceServer can be embedded to have forward compatible implementations.
type UnimplementedListServiceServer struct {
}

func (*UnimplementedListServiceServer) CreateList(ctx context.Context, req *CreateListsRequest) (*CreateListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateList not implemented")
}
func (*UnimplementedListServiceServer) AddTasksToList(ctx context.Context, req *AddTasksToListRequest) (*AddTasksToListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddTasksToList not implemented")
}
func (*UnimplementedListServiceServer) GetLists(ctx context.Context, req *MultiListRequest) (*MultiList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLists not implemented")
}
func (*UnimplementedListServiceServer) ToggleTasks(ctx context.Context, req *ToggleTaskRequest) (*ToggleTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ToggleTasks not implemented")
}

func RegisterListServiceServer(s *grpc.Server, srv ListServiceServer) {
	s.RegisterService(&_ListService_serviceDesc, srv)
}

func _ListService_CreateList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateListsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListServiceServer).CreateList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/list.ListService/CreateList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListServiceServer).CreateList(ctx, req.(*CreateListsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ListService_AddTasksToList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTasksToListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListServiceServer).AddTasksToList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/list.ListService/AddTasksToList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListServiceServer).AddTasksToList(ctx, req.(*AddTasksToListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ListService_GetLists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MultiListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListServiceServer).GetLists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/list.ListService/GetLists",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListServiceServer).GetLists(ctx, req.(*MultiListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ListService_ToggleTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToggleTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListServiceServer).ToggleTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/list.ListService/ToggleTasks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListServiceServer).ToggleTasks(ctx, req.(*ToggleTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ListService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "list.ListService",
	HandlerType: (*ListServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateList",
			Handler:    _ListService_CreateList_Handler,
		},
		{
			MethodName: "AddTasksToList",
			Handler:    _ListService_AddTasksToList_Handler,
		},
		{
			MethodName: "GetLists",
			Handler:    _ListService_GetLists_Handler,
		},
		{
			MethodName: "ToggleTasks",
			Handler:    _ListService_ToggleTasks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/list/list.proto",
}
